### PR TITLE
Light's modification

### PR DESCRIPTION
**Pull request by mixMugz**
Reworked internal lights in cockpit.

- Added some missed LIT textures to potentiometr 4 (Panel Light)
- Reworked ambient lights. Now it turn on/off depend of switch
- Reworked screen ambiend light. Now it works with workingtitle g3000 mod. Depends of screen brightness.
- Removed panel lights knob 100% off.
- Removed Landing Gear Warning when Throttle at zero
- Changed Pedestal lights remaped to Access switch
- Changed Panel Light knob at day start 0% at night 50%

### CODE REVIEW

**Comment by guifarias31** [comment]
Nice work. I just wanted to keep the Gear Warning at idle, since I think it's present on the real plane.

**Comment by mixMugz** [comment]
> Nice work. I just wanted to keep the Gear Warning at idle, since I think it's present on the real plane.

Realy? =) When throtle at iddle position it's alarm "Gear Warning"? But it's not logical. I keep worning for full flaps. But when you going from high altitude to low you switch throttle to idle (for speed management) and Gear Warning is annoyng. But anyway i can revert back

**Comment by mixMugz** [comment]
Reverted back Gear Warning

**Comment by guifarias31** [comment]
> > Nice work. I just wanted to keep the Gear Warning at idle, since I think it's present on the real plane.
> 
> Realy? =) When throtle at iddle position it's alarm "Gear Warning"? But it's not logical. I keep worning for full flaps. But when you going from high altitude to low you switch throttle to idle (for speed management) and Gear Warning is annoyng. But anyway i can revert back

You will most likely never put your throttle at idle on a turboprop, the drag generated by the propeller at idle is ENORMOUS, it's like a "propeller wall" in front of the plane. And if you think the warning is annoying, you can just place the throttle at around 1%.

**Pull request merged**
